# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'husky_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("husky.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.motorControl = QtWidgets.QGroupBox(self.frame)
        self.motorControl.setObjectName("motorControl")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.motorControl)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalControl = QtWidgets.QGroupBox(self.motorControl)
        self.horizontalControl.setObjectName("horizontalControl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.horizontalControl)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalControl)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalControl)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 1)
        self.motorSlider_4 = QtWidgets.QSlider(self.horizontalControl)
        self.motorSlider_4.setEnabled(False)
        self.motorSlider_4.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_4.setMinimum(1300)
        self.motorSlider_4.setMaximum(1700)
        self.motorSlider_4.setProperty("value", 1500)
        self.motorSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_4.setTickInterval(100)
        self.motorSlider_4.setObjectName("motorSlider_4")
        self.gridLayout_4.addWidget(self.motorSlider_4, 0, 4, 1, 1)
        self.motorSlider_1 = QtWidgets.QSlider(self.horizontalControl)
        self.motorSlider_1.setEnabled(False)
        self.motorSlider_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.motorSlider_1.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_1.setMinimum(1300)
        self.motorSlider_1.setMaximum(1700)
        self.motorSlider_1.setProperty("value", 1500)
        self.motorSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_1.setTickInterval(100)
        self.motorSlider_1.setObjectName("motorSlider_1")
        self.gridLayout_4.addWidget(self.motorSlider_1, 0, 0, 1, 1)
        self.motorSlider_2 = QtWidgets.QSlider(self.horizontalControl)
        self.motorSlider_2.setEnabled(False)
        self.motorSlider_2.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_2.setMinimum(1300)
        self.motorSlider_2.setMaximum(1700)
        self.motorSlider_2.setProperty("value", 1500)
        self.motorSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_2.setTickInterval(100)
        self.motorSlider_2.setObjectName("motorSlider_2")
        self.gridLayout_4.addWidget(self.motorSlider_2, 0, 2, 1, 1)
        self.motorSlider_3 = QtWidgets.QSlider(self.horizontalControl)
        self.motorSlider_3.setEnabled(False)
        self.motorSlider_3.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_3.setMinimum(1300)
        self.motorSlider_3.setMaximum(1700)
        self.motorSlider_3.setProperty("value", 1500)
        self.motorSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_3.setTickInterval(100)
        self.motorSlider_3.setObjectName("motorSlider_3")
        self.gridLayout_4.addWidget(self.motorSlider_3, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalControl)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalControl)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.horizontalControl, 0, 0, 1, 1)
        self.verticalControl = QtWidgets.QGroupBox(self.motorControl)
        self.verticalControl.setObjectName("verticalControl")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.verticalControl)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.motorSlider_5 = QtWidgets.QSlider(self.verticalControl)
        self.motorSlider_5.setEnabled(False)
        self.motorSlider_5.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_5.setMinimum(1300)
        self.motorSlider_5.setMaximum(1700)
        self.motorSlider_5.setProperty("value", 1500)
        self.motorSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_5.setTickInterval(100)
        self.motorSlider_5.setObjectName("motorSlider_5")
        self.gridLayout_5.addWidget(self.motorSlider_5, 0, 0, 1, 1)
        self.motorSlider_6 = QtWidgets.QSlider(self.verticalControl)
        self.motorSlider_6.setEnabled(False)
        self.motorSlider_6.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_6.setMinimum(1300)
        self.motorSlider_6.setMaximum(1700)
        self.motorSlider_6.setProperty("value", 1500)
        self.motorSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_6.setTickInterval(100)
        self.motorSlider_6.setObjectName("motorSlider_6")
        self.gridLayout_5.addWidget(self.motorSlider_6, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalControl)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalControl)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.verticalControl, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.motorControl)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.motorSlider_7 = QtWidgets.QSlider(self.groupBox_3)
        self.motorSlider_7.setEnabled(False)
        self.motorSlider_7.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_7.setMinimum(1300)
        self.motorSlider_7.setMaximum(1700)
        self.motorSlider_7.setProperty("value", 1500)
        self.motorSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_7.setTickInterval(100)
        self.motorSlider_7.setObjectName("motorSlider_7")
        self.horizontalLayout_2.addWidget(self.motorSlider_7)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.motorControl)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sensitivitySlider = QtWidgets.QSlider(self.frame_2)
        self.sensitivitySlider.setEnabled(False)
        self.sensitivitySlider.setStyleSheet("QSlider::handle:horizontal:disabled {background: rgb(0, 122, 217);}")
        self.sensitivitySlider.setMinimum(1)
        self.sensitivitySlider.setMaximum(5)
        self.sensitivitySlider.setProperty("value", 3)
        self.sensitivitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.sensitivitySlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sensitivitySlider.setTickInterval(1)
        self.sensitivitySlider.setObjectName("sensitivitySlider")
        self.horizontalLayout.addWidget(self.sensitivitySlider)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 3)
        self.gridLayout_3.setColumnStretch(0, 4)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setRowStretch(0, 9)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_2.addWidget(self.motorControl, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Husky Explorer"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.motorControl.setTitle(_translate("MainWindow", "Motor Control"))
        self.horizontalControl.setTitle(_translate("MainWindow", "Horizontal"))
        self.label_5.setText(_translate("MainWindow", "Motor 4"))
        self.label_4.setText(_translate("MainWindow", "Motor 3"))
        self.label_3.setText(_translate("MainWindow", "Motor 2"))
        self.label_2.setText(_translate("MainWindow", "Motor1"))
        self.verticalControl.setTitle(_translate("MainWindow", "Vertical"))
        self.label_6.setText(_translate("MainWindow", "Motor 5"))
        self.label_7.setText(_translate("MainWindow", "Motor 6"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Micro-ROV"))
        self.label.setText(_translate("MainWindow", "Sensitivity"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
