# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\shane\Documents\Code\HuskyROV\ui\pilot_terminal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 570)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("husky.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.motorFrame = QtWidgets.QGroupBox(self.frame)
        self.motorFrame.setObjectName("motorFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.motorFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalFrame = QtWidgets.QGroupBox(self.motorFrame)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.horizontalFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 1)
        self.motorSlider_4 = QtWidgets.QSlider(self.horizontalFrame)
        self.motorSlider_4.setEnabled(False)
        self.motorSlider_4.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_4.setMinimum(1300)
        self.motorSlider_4.setMaximum(1700)
        self.motorSlider_4.setProperty("value", 1500)
        self.motorSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_4.setTickInterval(100)
        self.motorSlider_4.setObjectName("motorSlider_4")
        self.gridLayout_4.addWidget(self.motorSlider_4, 0, 4, 1, 1)
        self.motorSlider_1 = QtWidgets.QSlider(self.horizontalFrame)
        self.motorSlider_1.setEnabled(False)
        self.motorSlider_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.motorSlider_1.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_1.setMinimum(1300)
        self.motorSlider_1.setMaximum(1700)
        self.motorSlider_1.setProperty("value", 1500)
        self.motorSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_1.setTickInterval(100)
        self.motorSlider_1.setObjectName("motorSlider_1")
        self.gridLayout_4.addWidget(self.motorSlider_1, 0, 0, 1, 1)
        self.motorSlider_2 = QtWidgets.QSlider(self.horizontalFrame)
        self.motorSlider_2.setEnabled(False)
        self.motorSlider_2.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_2.setMinimum(1300)
        self.motorSlider_2.setMaximum(1700)
        self.motorSlider_2.setProperty("value", 1500)
        self.motorSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_2.setTickInterval(100)
        self.motorSlider_2.setObjectName("motorSlider_2")
        self.gridLayout_4.addWidget(self.motorSlider_2, 0, 2, 1, 1)
        self.motorSlider_3 = QtWidgets.QSlider(self.horizontalFrame)
        self.motorSlider_3.setEnabled(False)
        self.motorSlider_3.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_3.setMinimum(1300)
        self.motorSlider_3.setMaximum(1700)
        self.motorSlider_3.setProperty("value", 1500)
        self.motorSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_3.setTickInterval(100)
        self.motorSlider_3.setObjectName("motorSlider_3")
        self.gridLayout_4.addWidget(self.motorSlider_3, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.horizontalFrame, 0, 0, 1, 1)
        self.verticalFrame = QtWidgets.QGroupBox(self.motorFrame)
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.verticalFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.motorSlider_5 = QtWidgets.QSlider(self.verticalFrame)
        self.motorSlider_5.setEnabled(False)
        self.motorSlider_5.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_5.setMinimum(1300)
        self.motorSlider_5.setMaximum(1700)
        self.motorSlider_5.setProperty("value", 1500)
        self.motorSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_5.setTickInterval(100)
        self.motorSlider_5.setObjectName("motorSlider_5")
        self.gridLayout_5.addWidget(self.motorSlider_5, 0, 0, 1, 1)
        self.motorSlider_6 = QtWidgets.QSlider(self.verticalFrame)
        self.motorSlider_6.setEnabled(False)
        self.motorSlider_6.setStyleSheet("QSlider::handle:vertical:disabled {background-color: rgb(0, 122, 217);}")
        self.motorSlider_6.setMinimum(1300)
        self.motorSlider_6.setMaximum(1700)
        self.motorSlider_6.setProperty("value", 1500)
        self.motorSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.motorSlider_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSlider_6.setTickInterval(100)
        self.motorSlider_6.setObjectName("motorSlider_6")
        self.gridLayout_5.addWidget(self.motorSlider_6, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.verticalFrame, 0, 1, 1, 1)
        self.sensitivityFrame = QtWidgets.QFrame(self.motorFrame)
        self.sensitivityFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensitivityFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensitivityFrame.setObjectName("sensitivityFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sensitivityFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.sensitivityFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sensitivitySlider = QtWidgets.QSlider(self.sensitivityFrame)
        self.sensitivitySlider.setEnabled(False)
        self.sensitivitySlider.setStyleSheet("QSlider::handle:horizontal:disabled {background: rgb(0, 122, 217);}")
        self.sensitivitySlider.setMinimum(1)
        self.sensitivitySlider.setMaximum(5)
        self.sensitivitySlider.setProperty("value", 3)
        self.sensitivitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.sensitivitySlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sensitivitySlider.setTickInterval(1)
        self.sensitivitySlider.setObjectName("sensitivitySlider")
        self.horizontalLayout.addWidget(self.sensitivitySlider)
        self.gridLayout_3.addWidget(self.sensitivityFrame, 1, 0, 1, 3)
        self.uRovFrame = QtWidgets.QGroupBox(self.motorFrame)
        self.uRovFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uRovFrame.sizePolicy().hasHeightForWidth())
        self.uRovFrame.setSizePolicy(sizePolicy)
        self.uRovFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uRovFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uRovFrame.setObjectName("uRovFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.uRovFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uMotorSlider = QtWidgets.QSlider(self.uRovFrame)
        self.uMotorSlider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMotorSlider.sizePolicy().hasHeightForWidth())
        self.uMotorSlider.setSizePolicy(sizePolicy)
        self.uMotorSlider.setAcceptDrops(False)
        self.uMotorSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uMotorSlider.setAutoFillBackground(False)
        self.uMotorSlider.setStyleSheet("")
        self.uMotorSlider.setMinimum(1300)
        self.uMotorSlider.setMaximum(1700)
        self.uMotorSlider.setProperty("value", 1500)
        self.uMotorSlider.setOrientation(QtCore.Qt.Vertical)
        self.uMotorSlider.setInvertedAppearance(False)
        self.uMotorSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.uMotorSlider.setTickInterval(100)
        self.uMotorSlider.setObjectName("uMotorSlider")
        self.verticalLayout.addWidget(self.uMotorSlider)
        self.uRovStatus = QtWidgets.QLabel(self.uRovFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uRovStatus.sizePolicy().hasHeightForWidth())
        self.uRovStatus.setSizePolicy(sizePolicy)
        self.uRovStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uRovStatus.setStyleSheet("color: rgb(0,180,0)")
        self.uRovStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.uRovStatus.setObjectName("uRovStatus")
        self.verticalLayout.addWidget(self.uRovStatus)
        self.gridLayout_3.addWidget(self.uRovFrame, 0, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 4)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setRowStretch(0, 9)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_2.addWidget(self.motorFrame, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.connectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.connectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_7.addWidget(self.connectButton, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.pilotConnected = QtWidgets.QPushButton(self.groupBox_2)
        self.pilotConnected.setEnabled(True)
        self.pilotConnected.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pilotConnected.setStyleSheet("QPushButton{color:rgb(180, 0, 0)}")
        self.pilotConnected.setObjectName("pilotConnected")
        self.gridLayout_7.addWidget(self.pilotConnected, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.copilotConnected = QtWidgets.QPushButton(self.groupBox_2)
        self.copilotConnected.setEnabled(True)
        self.copilotConnected.setFocusPolicy(QtCore.Qt.NoFocus)
        self.copilotConnected.setStyleSheet("QPushButton{color:rgb(180, 0, 0)}")
        self.copilotConnected.setObjectName("copilotConnected")
        self.gridLayout_7.addWidget(self.copilotConnected, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 2, 1, 1)
        self.portTextField = QtWidgets.QLineEdit(self.groupBox_2)
        self.portTextField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.portTextField.setObjectName("portTextField")
        self.gridLayout_7.addWidget(self.portTextField, 0, 3, 1, 1)
        self.disconnectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.disconnectButton.setEnabled(False)
        self.disconnectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.disconnectButton.setObjectName("disconnectButton")
        self.gridLayout_7.addWidget(self.disconnectButton, 0, 5, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Husky Explorer"))
        self.groupBox.setTitle(_translate("MainWindow", "ROV Output"))
        self.motorFrame.setTitle(_translate("MainWindow", "Motor Control"))
        self.horizontalFrame.setTitle(_translate("MainWindow", "Horizontal"))
        self.label_5.setText(_translate("MainWindow", "Motor 4"))
        self.label_4.setText(_translate("MainWindow", "Motor 3"))
        self.label_3.setText(_translate("MainWindow", "Motor 2"))
        self.label_2.setText(_translate("MainWindow", "Motor1"))
        self.verticalFrame.setTitle(_translate("MainWindow", "Vertical"))
        self.label_6.setText(_translate("MainWindow", "Motor 5"))
        self.label_7.setText(_translate("MainWindow", "Motor 6"))
        self.label.setText(_translate("MainWindow", "Sensitivity"))
        self.uRovFrame.setTitle(_translate("MainWindow", "Micro-ROV"))
        self.uRovStatus.setText(_translate("MainWindow", "Docked"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ROV"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.pilotConnected.setText(_translate("MainWindow", "Not Connected"))
        self.label_8.setText(_translate("MainWindow", "Co-Pilot:"))
        self.label_9.setText(_translate("MainWindow", "Pilot:"))
        self.copilotConnected.setText(_translate("MainWindow", "Not Connected"))
        self.label_11.setText(_translate("MainWindow", "Port"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

